### ISSUE TITLE
A queation about carafe_layer_kernel_cu.cpp

### ISSUE THREAD

**Issue by HB-X** [chensnathan/CARAFE_CUDA#1]
https://github.com/chensnathan/CARAFE_CUDA/blob/33d3d3af69b24fc679f6a3a071a19070dc46664b/carafe_layer/src/carafe_layer_kernel.cu#L49
https://github.com/chensnathan/CARAFE_CUDA/blob/33d3d3af69b24fc679f6a3a071a19070dc46664b/carafe_layer/src/carafe_layer_kernel.cu#L50

Maybe, the codes should be:
const int index_h = column_index / (orig_height * up_factor);
const int index_w = column_index / (orig_width * up_factor);

**Comment by chensnathan** [comment]
Hi, the tensor is in row-major order. So the code for getting the `index_h` and `index_w` is right.

**Comment by HB-X** [comment]
Thank you very much.
